---
- name: Configure firewall
  copy: src=client.rules dest=/etc/iptables.d/client.rules owner=root group=root mode=0640
  notify:
  - iptables

- name: Install graphical environments
  xbps: name={{ item }} state=present
  with_items:
    - xorg
    - lxde
    - awesome
    - i3
    - i3status
    - dmenu
    - xfce4
    - cinnamon
  notify:
    - lightdm

- name: Install editing suites
  xbps: name={{ item }} state=present
  with_items:
    - gedit
    - gimp
    - inkscape
    - libreoffice

- name: Install programming tools
  xbps: name={{ item }} state=present
  with_items:
    - base-devel
    - eclipse
    - codeblocks
    - ghc
    - git-all
    - openjdk
    - R
    - racket
    - spim
    - rust
    - cargo

- name: Install additional editors
  xbps: name={{ item }} state=present
  with_items:
    - emacs
    - neovim
    - python-neovim
    - python3.4-neovim
    - gvim
    - sublime-text3

- name: Install media playback programs
  xbps: name={{ item }} state=present
  with_items:
    - audacity
    - mpv
    - vlc

- name: Install additional misc. programs
  xbps: name={{ item }} state=present
  with_items:
    - dtrx
    - evince
    - firefox
    - gnupg2
    - google-chrome
    - redshift-gtk
    - htop
    - keepassx2
    - mlocate
    - mosh
    - redshift
    - rxvt-unicode
    - urxvt-perls
    - sl
    - tcpdump
    - tmux
    - tree
    - wine-32bit
    - wps-office
    - zsh

- name: Copy fix screens
  copy: src=fixScreens dest=/usr/local/bin/fixScreens owner=root group=root mode=0755

- name: Install lightdm
  xbps: pkg=lightdm state=present

- name: Make lightdm use system-auth
  file: src=/etc/pam.d/system-auth dest=/etc/pam.d/lightdm state=link force=yes

- include: greeter.yml

- name: Copy xdg autostarts
  copy: src={{ item }} dest=/etc/xdg/autostart/{{ item }} owner=root group=root mode=0644
  with_items:
    - xscreensaver.desktop
    - pc-client-linux.desktop

- name: Assures that app-default exists
  file: path=/usr/lib/X11/app-defaults state=directory

- name: Copy xscreensaver app-default config
  copy: src=XScreenSaver dest=/usr/lib/X11/app-defaults/XScreenSaver owner=root group=root mode=0644

- name: Copy sudoers file
  copy: src=cv.sudoers dest=/etc/sudoers.d/cv_local owner=root group=root mode=0644

- name: Copy change-password
  copy: src=change_password.py dest=/usr/local/bin/change-password owner=root group=root mode=0555

- name: Copy change-password Desktop file
  copy: src=change-password.desktop dest=/usr/share/applications/change-password.desktop owner=root group=root mode=0644

- name: Install change-password dependencies
  xbps: pkg=python-tkinter state=present

- name: Copy Old Session Killer
  copy: src=kill-old-users.sh dest=/usr/local/sbin/kill-old-users.sh owner=root group=root mode=0544

- name: Add Old Session Killer to Crontab
  copy: src=cleanup dest=/etc/cron.d/cleanup owner=root group=root mode=0544

- name: Enable various services
  file: src=/etc/sv/{{ item }} dest=/var/service/{{ item }} state=link owner=root group=root
  with_items:
    - dbus
    - lightdm
