---
- name: Check for iscan
  stat: path=/usr/bin/iscan
  register: iscan

- name: Download scanner packages
  get_url: url=https://download2.ebz.epson.net/iscan/plugin/gt-s650/deb/x64/iscan-gt-s650-bundle-1.0.0.x64.deb.tar.gz dest=/tmp/scan.tar.gz
  when: iscan.stat.exists == False

- name: Install xsane
  apt: name=xsane state=present
  when: iscan.stat.exists == False

- name: Create the scanner directory
  file: path=/tmp/scannerDriver state=directory owner=root group=root mode=0755
  when: iscan.stat.exists == False

- name: Expand the scanner archive
  unarchive: src=/tmp/scan.tar.gz dest=/tmp/scannerDriver copy=no
  when: iscan.stat.exists == False
  
- name: Install scanner packages
  command: ./install.sh chdir=/tmp/scannerDriver/iscan-gt-s650-bundle-1.0.0.x64.deb
  when: iscan.stat.exists == False
